### ISSUE TITLE
Region & Subregion Codes Source?

### ISSUE THREAD

**Issue by Omranic** [webpatser/laravel-countries#23]
Hello Dear @webpatser 
First of all thank you for this awesome package, I've just one question: From where have you obtained countries' region & subregion codes? I'm curios if there's some sort official reference or may be ISO list?

**Comment by Chalkin** [comment]
+1 for this

**Comment by hao-li** [comment]
It should be the UN M49.

https://unstats.un.org/unsd/methodology/m49

**Comment by BechirAhmed** [comment]
Is it possible and how to get the regions of countries?
