### ISSUE TITLE
Add support for ISO 639

### ISSUE THREAD

**Issue by yurtesen** [webpatser/laravel-countries#42]
I think it may be worthwhile to support ISO 639 language codes and maybe match them to country codes. I think geonames does it
https://github.com/ipalaus/geonames/wiki
http://download.geonames.org/export/dump/countryInfo.txt

**Comment by Tjoosten** [comment]
ISO 639: 3-letter codes or ISO 639: 2-letter codes?

**Comment by yurtesen** [comment]
I was thinking of 2 character codes.But this looked like a dead project so I decided to make my own package which is much more complete using geonames database. Now, I don't have to think about 2 or 3 characters, or population or gps location of a place or any other information which I may need, all is under control :)

https://github.com/yurtesen/geonames

So you can safely ignore this request. Thanks for the response.

**Comment by webpatser** [comment]
Since this in a countries list, and not a languages list, we have to think about adding these. Thanks for the input, and good luck on your new project..!
