### ISSUE TITLE
Add Kosova as country

### ISSUE THREAD

**Issue by valonsalihu1** [webpatser/laravel-countries#46]
Greetings,

I have used laravel-countries for a project of mine but Kosova is missing in the country list.
Kosova is new country and it is possible that some software application has not added it in the list.

You can read about Kosova in Wikidedia:
https://en.wikipedia.org/wiki/Kosovo

Thanks

**Comment by webpatser** [comment]
Since Kosovo has no ISO code assigned yet, we cannot add it yet until it's official :-)

> The code XK is being used by the European Commission,[19] Switzerland,[20] the Deutsche Bundesbank,[21] SWIFT,[22] and other organizations as a temporary country code for Kosovo.
