### ISSUE TITLE
laravel 5 migration refactoring

### ISSUE THREAD

**Issue by hammy4785** [webpatser/laravel-countries#48]
I wanted to bring it to your attention that your id on the countries table doesn't work with other tables when doing country_id. It needs to use increments instead of integer()->index() and primary(). It throws errors when you try to add foreign key on another table pointing to it otherwise.

**Comment by webpatser** [comment]
No. The ID field in the countries table is not an increment, since it's the increment from the official ISO database. That's why ID 1,2,3 is missing since those countries doesn't exist anymore.
