### ISSUE TITLE
Undefined Index currency

### ISSUE THREAD

**Issue by minedun6** [webpatser/laravel-countries#50]
No idea what seems to be wrong ?
`@foreach($countries as $country)
     <option value="{{ $country['country-code'] }}">{{ $country['name'] }}</option>
 @endforeach`

this works fine but when i do the same thing with 
`@foreach($countries as $country)
  <option value="{{ $country['currency_code'] }}">{{ $country['currency'] }}</option>
@endforeach`

this doesn't work and it prints out "Undefined Index: currency/currency_code"

**Comment by webpatser** [comment]
Since a few countries have no currency (like Antarctica) this field is not always in the array.

Just do a isset($country['currency_code']) first.
