### ISSUE TITLE
Why laravel-library and in /libraries?

### ISSUE THREAD

**Issue by kkomelin** [webpatser/laravel-countries#51]
Hello there,

I've just installed the project and noticed that it's been installed into /libraries.
What is the motivation of having it there instead of usual /vendor ?

Thanks,
Konstantin

**Comment by webpatser** [comment]
That was a small leftover from another internal project. I removed that in 1.5.2 and it should install in vendor now.

**Comment by kkomelin** [comment]
@webpatser Thanks
