### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by burhanturkce** [webpatser/laravel-countries#54]
Awesome job. I would like to thank you for this project.
And a question:
Are you planning to add timezone of the countries ?

**Comment by Scarwolf** [comment]
+

**Comment by multiwebinc** [comment]
Some countries have multiple timezones, so this would get messy. If you're trying to get a list of timezones, you can just do `DateTimeZone::listIdentifiers();`, which will return an array of timezones. In the case where a country only has one timezone, the entry will be of the format `Continent/Country`. See http://php.net/manual/en/timezones.php

**Comment by webpatser** [comment]
Also, since he timezone file is changing constantly @multiwebinc suggestion seems a better option.
