### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by JosephMendez** [webpatser/laravel-countries#56]

**Comment by stewis** [comment]
Hi,

It allows you to specify what column to show and order by on the select menus for example Countries::getListForSelect('citizenship') will create an array populated with the values of the citizenship column and the country id as it's key.

![screen shot 2016-11-23 at 10 38 51](https://cloud.githubusercontent.com/assets/1660946/20558720/59bf212c-b169-11e6-95a6-2bf2fe2fdf3c.png)

**Comment by webpatser** [comment]
?
