### ISSUE TITLE
5.4

### ISSUE THREAD

**Issue by DeeJaVu** [webpatser/laravel-countries#60]
```
CountriesServiceProvider.php line 72:
Call to undefined method Illuminate\Foundation\Application::share()
```

**Comment by creators** [comment]
```
src/Webpatser/Countries/CountriesServiceProvider.php:49
$this->app['command.countries.migration'] = $this->app->share(function($app)
```

[https://laravel.com/docs/5.4/upgrade](https://laravel.com/docs/5.4/upgrade)
### share Method Removed

The share method has been removed from the container. This was a legacy method that has not been documented in several years. If you are using this method, you should begin using the singleton method instead:

```
$container->singleton('foo', function () {
    return 'foo';
});
```

**Comment by webpatser** [comment]
The provider is fixed. Update to the 1.5.* tag in your composer.json :-)
