### ISSUE TITLE
sizeof(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by saqueib** [webpatser/laravel-countries#79]
I am getting this error while seeding the countries 

```ErrorException: sizeof(): Parameter must be an array or an object that implements Countable in ../../vendor/webpatser/laravel-countries/src/Webpatser/Countries/Countries.php:43```

If I remove the sizeof check it works.

```php
//Get the countries from the JSON file
// if (sizeof($this->countries) == 0){
    $this->countries = json_decode(file_get_contents(__DIR__ . '/Models/countries.json'), true);
//}

//Return the countries
return $this->countries;
```

initializing `protected $countries = [];` with empty array can fix it.

I am running PHP 7.2

**Comment by mm-x** [comment]
Same issue here but changed condition from

````if (sizeof($this->countries) == 0){````
to
````if (!$this->countries || sizeof($this->countries) == 0){````

**Comment by mateusfccp** [comment]
I did the same as @mm-x and it worked.

A cleaner solution would be to use `if (empty($this->countries)){`, as according to the documentations, when using `empty()`,

> A variable is considered empty if it does not exist or if its value equals FALSE.

and

>  The following things are considered to be empty:
> - "" (an empty string)
> - 0 (0 as an integer)
> - 0.0 (0 as a float)
> - "0" (0 as a string)
> - NULL
> - FALSE
> - array() (an empty array)
> - $var; (a variable declared, but without a value)

Thus, they are equivalent expressions.

This solution has been requested on pull-request https://github.com/webpatser/laravel-countries/pull/84.

**Comment by mateusfccp** [comment]
@saqueib If possible, close the issue, as the solution has already been merged. Thanks.

**Comment by affinitycloud** [comment]
This issue is still occurring and has not been fixed in dev-master.

**Comment by winonakwok** [comment]
Yes, issue has not been fixed in dev-master. I am currently using @mm-x 's suggestion as a temporary solution

**Comment by pihlersimon** [comment]
Still getting this error.

**Comment by garethdaine** [comment]
How come this issue keeps getting close when it still occurs?

**Comment by gabriel-cardoso** [comment]
It's merge in `develop` branch. It works if you specify `"webpatser/laravel-countries": "dev-develop"` in your `composer.json`

**Comment by iec989** [comment]
I did that @gabriel-cardoso, but now I'm getting the following error:
_Class 'Countries' not found_

**Comment by tomvo** [comment]
Seems to fix it for us too, could you tag this?

**Comment by mm-x** [comment]
@iec989 you may need to run composer dump-autoload

@mateusfccp late reply from me, I agree with your solution being better. Has this been merged yet? I read from the thread that it has been, but updating the package to dev-master, I get this strange error now
``` 
Non-static method Webpatser\Countries\Countries::getList() should not be called statically
```

**Comment by mateusfccp** [comment]
@mm-x I made a pull request and it has been merged. Some are complaining that it didn't work, though others are saying that it did work. There doesn't seem to be anything wrong with my code, and I don't think this error you are getting has nothing to do with my code (at least the error message doesn't imply it).

Anyway, I don't know why some are not getting it to work. If you have any hint, please, comment here so we can solve it!

**Comment by mm-x** [comment]
@mateusfccp Do you confirm the merge was made on master? When I browse the repo and go to the Countries.php class I observe this at line 43
```
        if (sizeof($this->countries) == 0){
            $this->countries = json_decode(file_get_contents(__DIR__ . '/Models/countries.json'), true);
        }
```
I have even tried removing the package from the project, deleted all files (migration + configs) reinstalled following the steps on the readme file, and now I am back to the error sizeof.

Assuming this was not merged right on dev-master or on another branch as mentioned above?

> It's merge in develop branch. It works if you specify "webpatser/laravel-countries": "dev-develop" in your composer.json

**Comment by mm-x** [comment]
Switching to dev-develop branch causes the same issue experienced by @iec989

**Comment by mateusfccp** [comment]
@mm-x I merged on develop, as it can be seen here:
https://github.com/webpatser/laravel-countries/blob/develop/src/Webpatser/Countries/Countries.php

I don't know if it should've been merged in another branch, for me it makes sense to merge to develop instead of master.

**Comment by tomvo** [comment]
Can we get this merged and tagged so the library doesn't break on > PHP 7?

**Comment by tomvo** [comment]
bump

**Comment by webocoders** [comment]
bump
