### ISSUE TITLE
Seeding sizeof() Error

### ISSUE THREAD

**Issue by sandofvega** [webpatser/laravel-countries#87]
When I run `php artisan migrate --seed` or `php artisan db:seed --class=CountriesSeeder`, an error show  to my terminal and no data inserted into the database:
```
In Countries.php line 43:
  sizeof(): Parameter must be an array or an object that implements Countable
```

**Comment by Filimoni** [comment]
Replacing line 43 of Countries.php from :
// if (sizeof($this->countries) == 0){
to :
if (is_null($this->countries) || empty($this->countries)) {
works for me.

**Comment by iec989** [comment]
I did that @Filimoni , but now I'm getting the following error:
Class 'Countries' not found

**Comment by RhRU** [comment]
When is this going to be implemented in the master branch?

**Comment by gabriel-cardoso** [comment]
For me, it was a PHP version issue. I was getting the error with PHP 7.2 but not with PHP 7.1 

I have both versions installed on my machine so I need to run `php7.1 artisan serve`

**Comment by PeteAtkins** [comment]
Any update on getting this merged? Its not in either branch as can be seen, as already mentioned, viewing the source on here.
Thanks
